name: ubuntu-terminal-app
version: 0.7.207
summary: Ubuntu Terminal app
description: The terminal app for all Ubuntu devices.
confinement: devmode
grade: devel

apps:
  ubuntu-terminal-app:
    command: desktop-launch $SNAP/bin/terminal.wrapper
    plugs: [unity7, opengl, network, network-bind, home, platform]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform

parts:
  wrapper:
    source: .
    plugin: dump
    organize:
      terminal.wrapper: bin/terminal.wrapper
    stage:
      - bin/terminal.wrapper
      - ubuntu-app-platform
    snap:
      - bin/terminal.wrapper
      - ubuntu-app-platform
    after: [desktop-ubuntu-app-platform]

  terminal:
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    source: .
    build-packages:
      - build-essential
      - cmake
      - gettext
      - intltool
      - python3
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqtermwidget5-0-dev
      - libpam0g-dev
    stage-packages:
      - sshpass
    snap:
      - -usr/share/doc
      - -usr/include
