name: ubuntu-terminal-app
version: "0.11"
summary: Ubuntu Terminal app
description: The terminal app for all Ubuntu devices.
confinement: devmode
grade: devel

apps:
  ubuntu-terminal-app:
    command: desktop-launch $SNAP/bin/terminal.wrapper
    desktop: usr/share/applications/ubuntu-terminal-app.desktop
    plugs: [unity7, unity8, opengl, network, network-bind, home, platform]

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  wrapper:
    source: snap
    plugin: dump
    organize:
      terminal.wrapper: bin/terminal.wrapper

  terminal:
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    source: .
    build-packages:
      - build-essential
      - cmake
      - gettext
      - intltool
      - python3
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqtermwidget5-0-dev
      - libpam0g-dev
      - xvfb
    stage-packages:
      - sshpass
      - fonts-inconsolata
    prime:
      - -usr/share/doc
      - -usr/include
    after: [desktop-ubuntu-app-platform]

  ubuntu-ui-extras:
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
    source: http://code.launchpad.net/~phablet-team/ubuntu-ui-extras/tabs
    source-type: bzr
    build-packages:
      - gettext
      - pkg-config
      - qtbase5-dev
      - qtdeclarative5-dev
      - libexiv2-dev
